### PR TITLE
Made the use of gulp more explicit

### PR DESCRIPTION
**Pull request by benhinchley**
but maybe not explicit enough

Should we have some sort of watch task inplace?

Signed-off-by: Benjamin Hinchley benjaminhinchley@gmail.com

### CODE REVIEW

**Comment by benhinchley** [comment]
yeah true true, might use browser-sync, am liking the debugging features a lot.

Would some like a _tests_ folder be a smart idea, like a simple html page with the current features on it, that imports the css, and runs like a lint on the css/scss or something???

**Comment by WhatsNewSaes** [comment]
I'd say we can hold off on that until we get the base functionality / direction in place

**Comment by benhinchley** [comment]
Okay, will do. will add a watch task and browser-sync task and then merge this in, and we can create a new issue about some sort of testing when we get to that point

**Comment by benhinchley** [comment]
I am going to leave the browser-sync task out for the time being, until we get more of the base laid out

**Pull request merged**
