### PR TITLE
Restructred the codebase

### PR DESCRIPTION
**Pull request by benhinchley**
Had a look at the code base, and didn't think it was structured the best, so gave it a restructure

### CODE REVIEW

**Comment by benhinchley** [comment]
@whatsnewsaes what do you think about these changes?

**Comment by WhatsNewSaes** [comment]
Took a look at these. What do you think we gain with this new structure?

**Comment by benhinchley** [comment]
I tried to give the project, a similar structure to many other Sass based projects I have seen on bower. It cleans up the root dir, and gives it a big more of a solid structure.

**Comment by benhinchley** [comment]
@whatsnewsaes are you okay for me to merge this?? or would you like to merge your Typography branch first??

**Pull request merged**
